### ISSUE TITLE
manage assets and more?

### ISSUE THREAD

**Issue by maxkomarychev** [isilher/red-vs-blue#1]
Hey, @isilher ,

first of all thank you for putting effort into this example.

I wanted to discuss something I noticed in your [readme](https://github.com/isilher/red-vs-blue#when-not-to-choose-this-approach):

> When NOT to choose this approach
> When you have to run a LOT of white label versions, you may want a setup that has a stricter separation between assets.

What kind of assets are you referring here? Icons? Something else beyond?

> When you want the white label versions to have differences beyond theme variables and feature flags. For example when different white labels will have different dependencies, you may be better off splitting into XCode targets/schemes and Android flavors. There is experimental support for this in react-native-ultimate-config if you still want to try to use it.

Are you referring to dependencies in native code? 

The reason I'm asking is that with recently introduced feature of [hooks](https://github.com/maxkomarychev/react-native-ultimate-config/blob/master/docs/api.md#hooks) it's now possible to intercept a moment when env is injected and do some custom operations like: copy assets into asset catalog and similar.

I'm curious to learn about your experience which led to such approach and I am sure it can be handled with rnuc to some extent.

> There is experimental support for this in react-native-ultimate-config if you still want to try to use it.

Unfortunately I hit some walls with these features: since they are *part of the build process* it could be a bit harder to implement certain functionality when project has rnuc as part of schemes/flavors and I am not entirely sure if they will ever get out of "experimental" incubator or even if they will if they will be able to carry all the functionality that CLI does.

Thanks,
Max.

**Comment by isilher** [comment]
Hi Max,

Thanks for your feedback! 

> What kind of assets are you referring here? Icons? Something else beyond?

I was thinking about icons, splash/launch-screens, notification images and such. Images used on the JS side could be structured, but you'd want to make sure they are not all bundled together for size.

> Are you referring to dependencies in native code?

Native and JS dependencies, although the later probably have less impact. I personally would steer away from creating white label apps with diverging code-bases, so I didn't give this much thought.

> The reason I'm asking is that with recently introduced feature of hooks it's now possible to intercept a moment when env is injected and do some custom operations like: copy assets into asset catalog and similar.
>
> I'm curious to learn about your experience which led to such approach and I am sure it can be handled with rnuc to some extent.

Interesting! I did read about this feature on your repository and made a mental note to check it out when setting up fastlane. I will look into your suggestion of copying assets when switching environments. For android that should just be a simple replacement of the `mipmap` directories, but I'm not sure yet how to approach swapping XCode's linked assets 🤔 . I'll give it a try.

> Unfortunately I hit some walls with these features: since they are part of the build process it could be a bit harder to implement certain functionality when project has rnuc as part of schemes/flavors and I am not entirely sure if they will ever get out of "experimental" incubator or even if they will if they will be able to carry all the functionality that CLI does.

That's unfortunate. Currently my goal is to avoid flavors and schemes so I didn't try it out, but I'll update the readme to reflect this. 

Cheers,
Rik

**Comment by isilher** [comment]
@maxkomarychev I tried the hook out and it works like a charm! For clarity I made a PR with the update (#2). Is this as you intended it?
