### ISSUE TITLE
How to use with require in image?

### ISSUE THREAD

**Issue by ArkanRomanPango** [isilher/red-vs-blue#13]
`require` is not allowed to use dynamic string. Is it possible to solve this issue with red vs blue? Or need to add an additional babel plugin only? https://stackoverflow.com/questions/69396249/react-native-whitelabel-application

If someone has any suggestions, I will be very grateful

**Comment by isilher** [comment]
red-vs-blue is just an example implementation of the react-native-ultimate-config library to set up a white label architecture.

To split assets between the labels, I would suggest to use the [hook](https://github.com/maxkomarychev/react-native-ultimate-config/blob/master/docs/api.md#hooks) in `.rnucrc.js` to copy the correct files from a label-specific directory into the asset-directory on setting the env. In red-vs-blue I did this specifically for native app icon assets (see #2). You could do the same with an image assets folder. 

Note that this would still assume that all images exist in all labels of the app. Only their contents would be overwritten from a library of label-specific flavours. This way, the `require` statements are not actually dynamic, but I think it does accomplish your goal (only the main asset folder is included in the bundle, with whatever label assets were copied there on setting the env).

**Comment by ArkanRomanPango** [comment]
@isilher thank you for response. I tried `.rnucrc.js` and it copied needed folder and good. But I can't use dynamically for `Image require`. Because I can't use some variable in `require` and if I add 2 `require` and use `if` I will get all images in result build

**Comment by isilher** [comment]
Could you give a more specific example of what you are trying to accomplish? The dynamic require is not going to work, but perhaps you could require a specific image file, and then override that file using the hook?

**Comment by ArkanRomanPango** [comment]
@isilher I already implemented solution with babel plugin. `babel-plugin-rn-white-label`. In this case, in the resulting bundle, I will have needed an image and easy to use. For example name of image will have name: `some-image.red.png` and `some-image.blue.png` but in react native you will use `require ('./images/some-image.png')` and babel will pick needed image according to `react native ultimate config` 
But 1 issue which exist - is I can't use absolute path in this case. `require ('src/featureName/images/some-image.png')` - will get an error
